import { useState } from 'react';
import { motion } from 'framer-motion';
import { Sparkles, Loader2, Upload, ArrowRight, Hash, Cpu, Layers, Activity, Image as ImageIcon } from 'lucide-react';
import axios from 'axios';

const API = 'http://localhost:8000';

const containerVariants = {
  hidden: { opacity: 0 },
  show: { opacity: 1, transition: { staggerChildren: 0.07 } }
};

const itemVariants = {
  hidden: { opacity: 0, y: 20 },
  show: { opacity: 1, y: 0, transition: { type: "spring", stiffness: 300, damping: 24 } }
};

export default function VaeView() {
  const [generatedUrl, setGeneratedUrl] = useState(null);
  const [isGenerating, setIsGenerating] = useState(false);

  const [selectedFile, setSelectedFile] = useState(null);
  const [previewUrl, setPreviewUrl] = useState(null);
  const [reconstructedUrl, setReconstructedUrl] = useState(null);
  const [isReconstructing, setIsReconstructing] = useState(false);

  const handleGenerate = async () => {
    setIsGenerating(true);
    try {
      const response = await axios.post(`${API}/api/vae/generate`);
      setGeneratedUrl(response.data.generated_image_url);
    } catch (error) {
      console.error('Error generating image:', error);
      alert('Failed to connect to backend.');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleFileChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      setSelectedFile(file);
      setPreviewUrl(URL.createObjectURL(file));
      setReconstructedUrl(null);
    }
  };

  const handleReconstruct = async () => {
    if (!selectedFile) return;
    setIsReconstructing(true);
    const formData = new FormData();
    formData.append('file', selectedFile);
    try {
      const response = await axios.post(`${API}/api/vae/reconstruct`, formData);
      setReconstructedUrl(response.data.reconstructed_image);
    } catch (error) {
      console.error('Error reconstructing:', error);
      alert('Failed to connect to backend.');
    } finally {
      setIsReconstructing(false);
    }
  };

  return (
    <motion.div
      variants={containerVariants}
      initial="hidden"
      animate="show"
      exit={{ opacity: 0, y: -20 }}
      className="space-y-8 max-w-6xl mx-auto"
    >
      {/* Header */}
      <header>
        <motion.div variants={itemVariants} className="flex items-center gap-3 mb-3">
          <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-secondary to-purple-400 flex items-center justify-center shadow-lg shadow-secondary/20">
            <Sparkles className="w-5 h-5 text-white" />
          </div>
          <div>
            <h2 className="text-3xl font-black gradient-text">Variational Autoencoder (VAE)</h2>
            <span className="badge badge-secondary">PRACT 2 — Generative Modeling &amp; Latent Interpolation</span>
          </div>
        </motion.div>
        <motion.p variants={itemVariants} className="text-slate-400 mt-2 max-w-3xl">
          Probabilistic encoder maps inputs to a Gaussian distribution in latent space (μ, σ²). 
          The reparameterization trick enables gradient-based sampling: z = μ + ε·σ, where ε ~ N(0,I). 
          Novel construction scenes are generated by sampling directly from the prior z ~ N(0, I).
        </motion.p>
      </header>

      {/* Architecture Diagram */}
      <motion.div variants={itemVariants} className="glass-panel p-6">
        <div className="section-title">
          <div className="section-icon"><Layers className="w-4 h-4" /></div>
          Network Architecture (with Reparameterization Trick)
        </div>
        <div className="arch-flow flex-wrap justify-center">
          <div className="arch-block arch-block-input">
            <div className="text-xs opacity-60">Input</div>
            <div className="font-bold">3×128×128</div>
          </div>
          <span className="arch-arrow">→</span>
          <div className="arch-block arch-block-encoder">
            <div className="text-xs opacity-60">4× Conv+BN</div>
            <div className="font-bold">Encoder</div>
          </div>
          <span className="arch-arrow">→</span>
          <div className="arch-block arch-block-encoder">
            <div className="text-xs opacity-60">FC → 256</div>
            <div className="font-bold">Flatten</div>
          </div>
          <span className="arch-arrow">→</span>

          {/* Split into mu and logvar */}
          <div className="flex flex-col gap-2 items-center">
            <div className="arch-block arch-block-latent" style={{ minWidth: '80px' }}>
              <div className="text-xs opacity-60">FC Head</div>
              <div className="font-bold">μ</div>
            </div>
            <div className="arch-block arch-block-latent" style={{ minWidth: '80px' }}>
              <div className="text-xs opacity-60">FC Head</div>
              <div className="font-bold">log σ²</div>
            </div>
          </div>

          <span className="arch-arrow">→</span>
          <div className="arch-block arch-block-latent animate-pulse-glow">
            <div className="text-xs opacity-60">z = μ + ε·σ</div>
            <div className="font-bold">Reparam.</div>
          </div>
          <span className="arch-arrow">→</span>
          <div className="arch-block arch-block-decoder">
            <div className="text-xs opacity-60">FC → 256×8×8</div>
            <div className="font-bold">Expand</div>
          </div>
          <span className="arch-arrow">→</span>
          <div className="arch-block arch-block-decoder">
            <div className="text-xs opacity-60">4× DeConv+BN</div>
            <div className="font-bold">Decoder</div>
          </div>
          <span className="arch-arrow">→</span>
          <div className="arch-block arch-block-output">
            <div className="text-xs opacity-60">Sigmoid</div>
            <div className="font-bold">3×128×128</div>
          </div>
        </div>
      </motion.div>

      {/* Model Info + Math */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <motion.div variants={itemVariants} className="glass-panel p-6">
          <div className="section-title">
            <div className="section-icon"><Cpu className="w-4 h-4" /></div>
            Model Configuration
          </div>
          <div className="info-grid">
            <div className="info-item">
              <span className="info-label">Latent Dim</span>
              <span className="info-value">256</span>
            </div>
            <div className="info-item">
              <span className="info-label">Parameters</span>
              <span className="info-value">~5.3M</span>
            </div>
            <div className="info-item">
              <span className="info-label">Input Size</span>
              <span className="info-value">128×128</span>
            </div>
            <div className="info-item">
              <span className="info-label">Channels</span>
              <span className="info-value">3 (RGB)</span>
            </div>
            <div className="info-item">
              <span className="info-label">Encoder</span>
              <span className="info-value">4 Conv</span>
            </div>
            <div className="info-item">
              <span className="info-label">μ, σ Heads</span>
              <span className="info-value">2 × FC</span>
            </div>
            <div className="info-item">
              <span className="info-label">β (KL weight)</span>
              <span className="info-value">1.0</span>
            </div>
            <div className="info-item">
              <span className="info-label">Prior</span>
              <span className="info-value">N(0, I)</span>
            </div>
          </div>
        </motion.div>

        <motion.div variants={itemVariants} className="glass-panel p-6">
          <div className="section-title">
            <div className="section-icon"><Hash className="w-4 h-4" /></div>
            Mathematical Formulation (ELBO)
          </div>
          <div className="math-block">
            <div>
              <span className="math-fn">ELBO Loss</span><span className="math-op">: </span>
              <span className="math-var">L</span> <span className="math-op">=</span> <span className="math-var">L</span><span className="math-sub">recon</span> <span className="math-op">+</span> <span className="math-var">β</span> <span className="math-op">·</span> <span className="math-var">D</span><span className="math-sub">KL</span>
            </div>
            <div className="mt-3">
              <span className="math-fn">Reconstruction</span><span className="math-op">: </span>
              <span className="math-var">L</span><span className="math-sub">recon</span> <span className="math-op">=</span> <span className="math-fn">MSE</span>(<span className="math-var">x</span>, <span className="math-var">x̂</span>)
              <span className="math-op"> = </span>
              <span className="math-op">Σ</span>(<span className="math-var">x</span><span className="math-sub">i</span> <span className="math-op">−</span> <span className="math-var">x̂</span><span className="math-sub">i</span>)<span className="math-sup">2</span>
            </div>
            <div className="mt-3">
              <span className="math-fn">KL Divergence</span><span className="math-op">: </span>
              <span className="math-var">D</span><span className="math-sub">KL</span> <span className="math-op">=</span> <span className="math-op">−½ · Σ</span>(1 <span className="math-op">+</span> <span className="math-fn">log</span> <span className="math-var">σ</span><span className="math-sup">2</span> <span className="math-op">−</span> <span className="math-var">μ</span><span className="math-sup">2</span> <span className="math-op">−</span> <span className="math-var">σ</span><span className="math-sup">2</span>)
            </div>
            <div className="mt-3">
              <span className="math-fn">Reparameterization</span><span className="math-op">: </span>
              <span className="math-var">z</span> <span className="math-op">=</span> <span className="math-var">μ</span> <span className="math-op">+</span> <span className="math-var">ε</span> <span className="math-op">·</span> <span className="math-var">σ</span>
              <span className="math-op"> , where </span>
              <span className="math-var">ε</span> <span className="math-op">~</span> <span className="math-fn">N</span>(0, <span className="math-var">I</span>)
            </div>
            <span className="math-label">Maximize Evidence Lower Bound = minimize reconstruction + regularize latent to prior</span>
          </div>
        </motion.div>
      </div>

      {/* Two-mode Inference: Generate + Reconstruct */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Generate Mode */}
        <motion.div variants={itemVariants} className="glass-panel p-6">
          <div className="section-title">
            <div className="section-icon"><Sparkles className="w-4 h-4" /></div>
            Generate Novel Sample (z ~ N(0, I))
          </div>
          <div className="flex flex-col items-center gap-5">
            <button onClick={handleGenerate} disabled={isGenerating} className="btn-gradient w-full">
              {isGenerating ? (
                <>Sampling <Loader2 className="w-5 h-5 animate-spin" /></>
              ) : (
                <>Sample Latent Space <Sparkles className="w-5 h-5" /></>
              )}
            </button>
            <div className="image-frame h-64 w-full">
              {generatedUrl ? (
                <motion.img initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }}
                  src={generatedUrl} alt="Generated VAE Sample" className="w-full h-full object-cover" />
              ) : (
                <div className="text-slate-600 text-sm font-medium flex flex-col items-center">
                  <Sparkles className="w-10 h-10 mb-2 opacity-20" />
                  Click to generate
                </div>
              )}
            </div>
          </div>
        </motion.div>

        {/* Reconstruct Mode */}
        <motion.div variants={itemVariants} className="glass-panel p-6">
          <div className="section-title">
            <div className="section-icon"><ImageIcon className="w-4 h-4" /></div>
            Reconstruct Uploaded Image
          </div>
          <div className="flex flex-col items-center gap-4">
            <label className="upload-zone h-32 w-full">
              {previewUrl ? (
                <img src={previewUrl} alt="Input" className="w-full h-full object-cover opacity-80 group-hover:opacity-100 transition-opacity" />
              ) : (
                <div className="flex flex-col items-center py-3">
                  <Upload className="w-8 h-8 mb-2 text-slate-500" />
                  <span className="text-xs text-slate-400">Upload construction site image</span>
                </div>
              )}
              <input type="file" className="hidden" accept="image/*" onChange={handleFileChange} />
            </label>
            <button onClick={handleReconstruct} disabled={!selectedFile || isReconstructing} className="btn-secondary w-full">
              {isReconstructing ? (
                <>Reconstructing <Loader2 className="w-5 h-5 animate-spin" /></>
              ) : (
                <>Reconstruct <ArrowRight className="w-5 h-5" /></>
              )}
            </button>
            <div className="image-frame h-40 w-full">
              {reconstructedUrl ? (
                <motion.img initial={{ opacity: 0 }} animate={{ opacity: 1 }}
                  src={reconstructedUrl} alt="VAE Reconstruction" className="w-full h-full object-cover" />
              ) : (
                <div className="text-slate-600 text-sm">Awaiting upload</div>
              )}
            </div>
          </div>
        </motion.div>
      </div>

      {/* Training Metrics */}
      <motion.div variants={itemVariants}>
        <div className="section-title">
          <div className="section-icon"><Activity className="w-4 h-4" /></div>
          Training Metrics &amp; Latent Space Analysis
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="glass-panel-hover p-4 h-80 flex flex-col">
            <h4 className="text-sm font-semibold text-slate-400 mb-2">ELBO Loss Curve (Reconstruction + KL)</h4>
            <div className="flex-1 relative rounded-lg overflow-hidden bg-slate-900/50">
              <img src={`${API}/data/processed/features/vae_loss_curve.png`} className="w-full h-full object-contain" alt="VAE Loss"
                onError={(e) => { e.target.style.display = 'none'; e.target.nextSibling.style.display = 'flex'; }} />
              <div className="absolute inset-0 hidden items-center justify-center text-slate-500 text-sm">Run notebook to generate</div>
            </div>
          </div>
          <div className="glass-panel-hover p-4 h-80 flex flex-col">
            <h4 className="text-sm font-semibold text-slate-400 mb-2">Latent Manifold (t-SNE Projection)</h4>
            <div className="flex-1 relative rounded-lg overflow-hidden bg-slate-900/50">
              <img src={`${API}/data/processed/features/vae_tsne.png`} className="w-full h-full object-contain" alt="VAE t-SNE"
                onError={(e) => { e.target.style.display = 'none'; e.target.nextSibling.style.display = 'flex'; }} />
              <div className="absolute inset-0 hidden items-center justify-center text-slate-500 text-sm">Run notebook to generate</div>
            </div>
          </div>
        </div>
      </motion.div>

      {/* Saved Outputs */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <motion.div variants={itemVariants} className="glass-panel-hover p-6">
          <h3 className="text-lg font-bold text-slate-200 mb-3">VAE Generative Samples (from Prior)</h3>
          <div className="image-frame h-64">
            <img src={`${API}/data/processed/features/vae_generative_samples.png`} alt="VAE Samples" className="w-full h-full object-contain"
              onError={(e) => { e.target.style.display = 'none'; e.target.nextSibling.style.display = 'flex'; }} />
            <div className="absolute inset-0 hidden items-center justify-center text-slate-500 text-sm">Run notebook to generate</div>
          </div>
        </motion.div>
        <motion.div variants={itemVariants} className="glass-panel-hover p-6">
          <h3 className="text-lg font-bold text-slate-200 mb-3">Original vs Reconstructed</h3>
          <div className="image-frame h-64">
            <img src={`${API}/data/processed/features/vae_original_vs_reconstructed.png`} alt="VAE Comparison" className="w-full h-full object-contain"
              onError={(e) => { e.target.style.display = 'none'; e.target.nextSibling.style.display = 'flex'; }} />
            <div className="absolute inset-0 hidden items-center justify-center text-slate-500 text-sm">Run notebook to generate</div>
          </div>
        </motion.div>
      </div>

      {/* SSIM/PSNR Metrics */}
      <motion.div variants={itemVariants} className="glass-panel-hover p-6">
        <h3 className="text-lg font-bold text-slate-200 mb-3">VAE Metrics (SSIM / PSNR)</h3>
        <div className="image-frame h-64">
          <img src={`${API}/data/processed/features/vae_metrics.png`} alt="VAE Metrics" className="w-full h-full object-contain"
            onError={(e) => { e.target.style.display = 'none'; e.target.nextSibling.style.display = 'flex'; }} />
          <div className="absolute inset-0 hidden items-center justify-center text-slate-500 text-sm">Run notebook to generate</div>
        </div>
      </motion.div>
    </motion.div>
  );
}
